Refactor tests.
dmdevgo/RxPM pull request #22
Opened 2018-07-25 07:02 UTC by Jeevuz

Use mockito-kotlin, change big tests in favor of small ones. One test code style (setUp name, annotation in one line, etc.)

Regarding discussed buffer tests: I've checked rewritten versions twice to ensure that they fails on the old buffer variant and is ok with fixed one. So I sure they are ok.

2018-07-26 21:08 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/PmExtensionsTest.kt
> -    fun testMaybeEmptyBindProgress() {
Почему вариант с empty удален?

2018-07-26 21:09 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/PmExtensionsTest.kt
> +        Single.error<Int>(error)
Почему Single а не Maybe?

2018-07-26 21:46 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/delegate/PmControllerDelegateTest.kt
> +            PresentationModel.Lifecycle.CREATED,
Использовать импорт PresentationModel.Lifecycle

2018-07-26 21:57 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/navigation/NavigationMessageDispatcherTest.kt
> +    private fun createDispatcher(handlers: List<Any>): NavigationMessageDispatcher {
Может переименовать - createDispatcherChain ?

2018-07-26 21:59 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/CheckControlTest.kt
> +            .assertValues(
assertOnlyValues ?

2018-07-26 22:02 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/DialogControlTest.kt
> +        dialogControl.showForResult(Unit).subscribe()
Может просто show(Unit)

2018-07-26 22:06 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/DialogControlTest.kt
> +            .assertSubscribed()
assertEmpty

2018-07-26 22:10 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/DialogControlTest.kt
> +            .assertSubscribed()
assertEmpty

2018-07-26 22:12 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/InputControlTest.kt
> +            .assertValues(
assertValuesOnly

2018-07-26 22:12 UTC, dmdevgo commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/InputControlTest.kt
> +            .assertValues(
assertValuesOnly

2018-07-26 22:29 UTC, dmdevgo requested changes
Почти все ок

2018-08-15 11:37 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/PmExtensionsTest.kt
> +        Single.error<Int>(error)
Ошибся, надо исправить.

2018-08-15 11:39 UTC, Jeevuz reviewed
Проверю.

2018-08-15 11:39 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/PmExtensionsTest.kt
> +        Single.error<Int>(error)
Пробуем ревью ;)

2018-08-15 11:39 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/PmExtensionsTest.kt
> +            .bindProgress(progress)
Продолжаем пробу ревью.

2018-08-15 12:12 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/delegate/PmControllerDelegateTest.kt
> +            PresentationModel.Lifecycle.CREATED,
Да, можно. И надо попробовать тут assertValuesOnly(). Вроде подходит хорошо. 
И то же в 2х других делегатах сделать.

2018-08-20 08:54 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/navigation/NavigationMessageDispatcherTest.kt
> +    private fun createDispatcher(handlers: List<Any>): NavigationMessageDispatcher {
Ну мы же создаем диспатчер тут, он же возвращается. А то что там набор хендлеров используется - видно из параметров. Я бы не менял имя.

2018-08-20 08:57 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/DialogControlTest.kt
> +        dialogControl.showForResult(Unit).subscribe()
Не, я же тут вообще нигде в тесте show не использую. show упрощенная версия showForResult. Если showForResult работает, то show и подавно. Такая логика у меня тут. Поэтому я бы не менял.

2018-08-20 08:59 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/DialogControlTest.kt
> +            .assertSubscribed()
У него assertNotComplete(), поэтому не подходит.

2018-08-20 08:59 UTC, Jeevuz commented on rxpm/src/test/kotlin/me/dmdev/rxpm/widget/DialogControlTest.kt
> +            .assertSubscribed()
У него assertNotComplete(), поэтому не подходит.

2018-08-20 09:11 UTC, Jeevuz commented
Досмотрел. Два первых поправить стоит, остальное не трогал бы.

2018-08-27 07:37 UTC, Jeevuz commented
Поправил что хотели. Плюс после добавления AndroidSchedulers.mainThread для навигации в делегатах, пришлось добавлять Rule для подмены шедулеров, пригодится еще где-нибудь потом, если будем писать тесты на bind различные.

2018-08-27 21:38 UTC, dmdevgo approved these changes

2018-08-27 21:38 UTC, merged